on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Service to Rollback'
        required: true
        default: 'FilesQL' 
        type: choice
        options:
        - AnalyticsQL
        - BiochemQL
        - ChemspaceQL
        - ContainerQL
        - EnzymeQL
        - FilesQL
        - InstumentQL        
        - InventoryQL
        - LCMSQL
        - MaldiQL
        - WorkflowQL
      print_tags:
        description: 'True to print to STDOUT'
        required: true 
        type: boolean 
      tags:
        description: 'Hash to Rollback to!'
        required: false 
        type: string
      environment_builtin:
        description: 'Environment to Rollback!'
        type: environment
        required: true 

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ github.event.inputs.print_tags == 'true' }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ github.event.inputs.tags }} 
